// Code generated by "stringer -type=Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[IDENT-1]
	_ = x[LITERAL-2]
	_ = x[ADD-3]
	_ = x[SUB-4]
	_ = x[MUL-5]
	_ = x[DIV-6]
	_ = x[MOD-7]
	_ = x[EQU-8]
	_ = x[NEQ-9]
	_ = x[LSS-10]
	_ = x[LEQ-11]
	_ = x[GTR-12]
	_ = x[GEQ-13]
	_ = x[AND-14]
	_ = x[OR-15]
	_ = x[NOT-16]
	_ = x[ADD_ASSIGN-17]
	_ = x[SUB_ASSIGN-18]
	_ = x[MUL_ASSIGN-19]
	_ = x[DIV_ASSIGN-20]
	_ = x[MOD_ASSIGN-21]
	_ = x[BITAND-22]
	_ = x[BITOR-23]
	_ = x[BITXOR-24]
	_ = x[ANDAND-25]
	_ = x[OROR-26]
	_ = x[ASSIGN-27]
	_ = x[DOUBLE_ASSIGN-28]
	_ = x[COMMA-29]
	_ = x[SEMI-30]
	_ = x[RdrOut-31]
	_ = x[AppOut-32]
	_ = x[RdrIn-33]
	_ = x[TILDE-34]
	_ = x[EXCL-35]
	_ = x[COLON-36]
	_ = x[DOUBLE_COLON-37]
	_ = x[LPAREN-38]
	_ = x[RPAREN-39]
	_ = x[LBRACE-40]
	_ = x[RBRACE-41]
	_ = x[LBRACK-42]
	_ = x[RBRACK-43]
	_ = x[AT-44]
	_ = x[REM-45]
	_ = x[IF-46]
	_ = x[ELSE-47]
	_ = x[GOTO-48]
	_ = x[FOR-49]
	_ = x[DO-50]
	_ = x[IN-51]
	_ = x[CALL-52]
	_ = x[EOF-53]
}

const _Token_name = "ILLEGALIDENTLITERAL+-*/%EQUNEQLSSLEQGTRGEQANDORNOT+=-=*=/=%=&|^&&||===,;>>><~!:::(){}[]@RemifelsegotofordoinCallEOF"

var _Token_index = [...]uint8{0, 7, 12, 19, 20, 21, 22, 23, 24, 27, 30, 33, 36, 39, 42, 45, 47, 50, 52, 54, 56, 58, 60, 61, 62, 63, 65, 67, 68, 70, 71, 72, 73, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 91, 93, 97, 101, 104, 106, 108, 112, 115}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
