// Code generated by "stringer -type=Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[NUM-3]
	_ = x[STR-4]
	_ = x[TRUE-5]
	_ = x[FALSE-6]
	_ = x[ASSIGN-7]
	_ = x[PLUS-8]
	_ = x[MINUS-9]
	_ = x[COLON_ASSIGN-10]
	_ = x[INC-11]
	_ = x[DEC-12]
	_ = x[AT-13]
	_ = x[ASTERISK-14]
	_ = x[SLASH-15]
	_ = x[MOD-16]
	_ = x[POWER-17]
	_ = x[HASH-18]
	_ = x[REFERENCE-19]
	_ = x[OR-20]
	_ = x[AND-21]
	_ = x[CONCAT-22]
	_ = x[LT-23]
	_ = x[GT-24]
	_ = x[EQ-25]
	_ = x[NEQ-26]
	_ = x[LEQ-27]
	_ = x[GEQ-28]
	_ = x[DOCS-29]
	_ = x[COMMA-30]
	_ = x[SEMICOLON-31]
	_ = x[COLON-32]
	_ = x[DOT-33]
	_ = x[NS-34]
	_ = x[LPAREN-35]
	_ = x[RPAREN-36]
	_ = x[LBRACE-37]
	_ = x[RBRACE-38]
	_ = x[LBRACKET-39]
	_ = x[RBRACKET-40]
	_ = x[MODLIT-41]
	_ = x[IMPORT-42]
	_ = x[FROM-43]
	_ = x[AS-44]
	_ = x[LET-45]
	_ = x[VAR-46]
	_ = x[CONST-47]
	_ = x[FN-48]
	_ = x[RETURN-49]
	_ = x[IF-50]
	_ = x[ELSE-51]
	_ = x[MATCH-52]
	_ = x[LOOP-53]
	_ = x[DO-54]
	_ = x[PUB-55]
	_ = x[FINAL-56]
	_ = x[STATIC-57]
	_ = x[COMPTIME-58]
	_ = x[UNSAFE-59]
	_ = x[CLASS-60]
	_ = x[EXTENDS-61]
	_ = x[IMPL-62]
	_ = x[FOR-63]
	_ = x[NEW-64]
	_ = x[DELETE-65]
	_ = x[EXTENSIONS-66]
	_ = x[TRY-67]
	_ = x[CATCH-68]
	_ = x[FINALLY-69]
	_ = x[THROW-70]
	_ = x[THROWS-71]
}

const _Token_name = "ILLEGALEOFIDENTNUMSTRtruefalse=+-:=++--@*/%**#$||&&&<>==!=<=>=',;:.::(){}[]modimportfromasletvarconstfnreturnifelsematchloopdopubfinalstaticcomptimeunsafeclassextendsimplfornewdeleteextensionstrycatchfinallythrowthrows"

var _Token_index = [...]uint8{0, 7, 10, 15, 18, 21, 25, 30, 31, 32, 33, 35, 37, 39, 40, 41, 42, 43, 45, 46, 47, 49, 51, 52, 53, 54, 56, 58, 60, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 78, 84, 88, 90, 93, 96, 101, 103, 109, 111, 115, 120, 124, 126, 129, 134, 140, 148, 154, 159, 166, 170, 173, 176, 182, 192, 195, 200, 207, 212, 218}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
