// Code generated by "stringer -type=Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[NUM-3]
	_ = x[STR-4]
	_ = x[TRUE-5]
	_ = x[FALSE-6]
	_ = x[ASSIGN-7]
	_ = x[PLUS-8]
	_ = x[MINUS-9]
	_ = x[COLON_ASSIGN-10]
	_ = x[PLUS_ASSIGN-11]
	_ = x[MINUS_ASSIGN-12]
	_ = x[ASTERISK_ASSIGN-13]
	_ = x[SLASH_ASSIGN-14]
	_ = x[MOD_ASSIGN-15]
	_ = x[AND_ASSIGN-16]
	_ = x[OR_ASSIGN-17]
	_ = x[POWER_ASSIGN-18]
	_ = x[INC-19]
	_ = x[DEC-20]
	_ = x[AT-21]
	_ = x[ASTERISK-22]
	_ = x[SLASH-23]
	_ = x[MOD-24]
	_ = x[POWER-25]
	_ = x[HASH-26]
	_ = x[REFERENCE-27]
	_ = x[OR-28]
	_ = x[AND-29]
	_ = x[CONCAT-30]
	_ = x[LT-31]
	_ = x[GT-32]
	_ = x[NOT-33]
	_ = x[QUEST-34]
	_ = x[EQ-35]
	_ = x[NEQ-36]
	_ = x[LE-37]
	_ = x[GE-38]
	_ = x[DOCS-39]
	_ = x[COMMA-40]
	_ = x[SEMICOLON-41]
	_ = x[COLON-42]
	_ = x[DOT-43]
	_ = x[NS-44]
	_ = x[LPAREN-45]
	_ = x[RPAREN-46]
	_ = x[LBRACE-47]
	_ = x[RBRACE-48]
	_ = x[LBRACKET-49]
	_ = x[RBRACKET-50]
	_ = x[MODLIT-51]
	_ = x[IMPORT-52]
	_ = x[FROM-53]
	_ = x[AS-54]
	_ = x[LET-55]
	_ = x[VAR-56]
	_ = x[CONST-57]
	_ = x[FN-58]
	_ = x[RETURN-59]
	_ = x[IF-60]
	_ = x[ELSE-61]
	_ = x[MATCH-62]
	_ = x[LOOP-63]
	_ = x[DO-64]
	_ = x[PUB-65]
	_ = x[FINAL-66]
	_ = x[STATIC-67]
	_ = x[COMPTIME-68]
	_ = x[UNSAFE-69]
	_ = x[CLASS-70]
	_ = x[EXTENDS-71]
	_ = x[IMPL-72]
	_ = x[FOR-73]
	_ = x[NEW-74]
	_ = x[DELETE-75]
	_ = x[EXTENSIONS-76]
	_ = x[TRY-77]
	_ = x[CATCH-78]
	_ = x[FINALLY-79]
	_ = x[THROW-80]
	_ = x[THROWS-81]
}

const _Token_name = "ILLEGALEOFIDENTNUMSTRtruefalse=+-:=+=-=*=/=%=&&=||=**=++--@*/%**#$||&&&<>!?==!=<=>=',;:.::(){}[]modimportfromasletvarconstfnreturnifelsematchloopdopubfinalstaticcomptimeunsafeclassextendsimplfornewdeleteextensionstrycatchfinallythrowthrows"

var _Token_index = [...]uint8{0, 7, 10, 15, 18, 21, 25, 30, 31, 32, 33, 35, 37, 39, 41, 43, 45, 48, 51, 54, 56, 58, 59, 60, 61, 62, 64, 65, 66, 68, 70, 71, 72, 73, 74, 75, 77, 79, 81, 83, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 99, 105, 109, 111, 114, 117, 122, 124, 130, 132, 136, 141, 145, 147, 150, 155, 161, 169, 175, 180, 187, 191, 194, 197, 203, 213, 216, 221, 228, 233, 239}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
