// Code generated by "stringer -type=Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[NUM-3]
	_ = x[STR-4]
	_ = x[TRUE-5]
	_ = x[FALSE-6]
	_ = x[ASSIGN-7]
	_ = x[PLUS-8]
	_ = x[MINUS-9]
	_ = x[COLON_ASSIGN-10]
	_ = x[INC-11]
	_ = x[DEC-12]
	_ = x[AT-13]
	_ = x[ASTERISK-14]
	_ = x[SLASH-15]
	_ = x[MOD-16]
	_ = x[POWER-17]
	_ = x[HASH-18]
	_ = x[REFERENCE-19]
	_ = x[OR-20]
	_ = x[AND-21]
	_ = x[CONCAT-22]
	_ = x[LT-23]
	_ = x[GT-24]
	_ = x[NOT-25]
	_ = x[QUEST-26]
	_ = x[EQ-27]
	_ = x[NEQ-28]
	_ = x[LE-29]
	_ = x[GE-30]
	_ = x[DOCS-31]
	_ = x[COMMA-32]
	_ = x[SEMICOLON-33]
	_ = x[COLON-34]
	_ = x[DOT-35]
	_ = x[NS-36]
	_ = x[LPAREN-37]
	_ = x[RPAREN-38]
	_ = x[LBRACE-39]
	_ = x[RBRACE-40]
	_ = x[LBRACKET-41]
	_ = x[RBRACKET-42]
	_ = x[MODLIT-43]
	_ = x[IMPORT-44]
	_ = x[FROM-45]
	_ = x[AS-46]
	_ = x[LET-47]
	_ = x[VAR-48]
	_ = x[CONST-49]
	_ = x[FN-50]
	_ = x[RETURN-51]
	_ = x[IF-52]
	_ = x[ELSE-53]
	_ = x[MATCH-54]
	_ = x[LOOP-55]
	_ = x[DO-56]
	_ = x[PUB-57]
	_ = x[FINAL-58]
	_ = x[STATIC-59]
	_ = x[COMPTIME-60]
	_ = x[UNSAFE-61]
	_ = x[CLASS-62]
	_ = x[EXTENDS-63]
	_ = x[IMPL-64]
	_ = x[FOR-65]
	_ = x[NEW-66]
	_ = x[DELETE-67]
	_ = x[EXTENSIONS-68]
	_ = x[TRY-69]
	_ = x[CATCH-70]
	_ = x[FINALLY-71]
	_ = x[THROW-72]
	_ = x[THROWS-73]
}

const _Token_name = "ILLEGALEOFIDENTNUMSTRtruefalse=+-:=++--@*/%**#$||&&&<>!?==!=<=>=',;:.::(){}[]modimportfromasletvarconstfnreturnifelsematchloopdopubfinalstaticcomptimeunsafeclassextendsimplfornewdeleteextensionstrycatchfinallythrowthrows"

var _Token_index = [...]uint8{0, 7, 10, 15, 18, 21, 25, 30, 31, 32, 33, 35, 37, 39, 40, 41, 42, 43, 45, 46, 47, 49, 51, 52, 53, 54, 55, 56, 58, 60, 62, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 80, 86, 90, 92, 95, 98, 103, 105, 111, 113, 117, 122, 126, 128, 131, 136, 142, 150, 156, 161, 168, 172, 175, 178, 184, 194, 197, 202, 209, 214, 220}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
