// Code generated by "stringer -type=Modifier -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModNone-0]
	_ = x[ModHidden-1]
	_ = x[ModStatic-2]
}

const _Modifier_name = "hiddenstatic"

var _Modifier_index = [...]uint8{0, 0, 6, 12}

func (i Modifier) String() string {
	if i < 0 || i >= Modifier(len(_Modifier_index)-1) {
		return "Modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifier_name[_Modifier_index[i]:_Modifier_index[i+1]]
}
