// Code generated by "stringer -type=RuleID -linecomment -output=hcr_string.go"; DO NOT EDIT.

package bash

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RuleIllegal-0]
	_ = x[RuleMutilString-1]
	_ = x[RuleBoolFormat-2]
}

const _RuleID_name = "illegalmutil_stringbool_format"

var _RuleID_index = [...]uint8{0, 7, 19, 30}

func (i RuleID) String() string {
	if i >= RuleID(len(_RuleID_index)-1) {
		return "RuleID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RuleID_name[_RuleID_index[i]:_RuleID_index[i+1]]
}
