// Code generated by "stringer -type=FieldModifier -linecomment"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldModifierNone-0]
	_ = x[FieldModifierRequired-1]
	_ = x[FieldModifierOptional-2]
	_ = x[FieldModifierReadonly-3]
	_ = x[FieldModifierStatic-4]
	_ = x[FieldModifierPub-5]
}

const _FieldModifier_name = "nonerequired?readonlystaticpub"

var _FieldModifier_index = [...]uint8{0, 4, 12, 13, 21, 27, 30}

func (i FieldModifier) String() string {
	if i < 0 || i >= FieldModifier(len(_FieldModifier_index)-1) {
		return "FieldModifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldModifier_name[_FieldModifier_index[i]:_FieldModifier_index[i+1]]
}
