compilerOptions:
  bash:
  batch:
    commentSyntax: rem
  vbs:
main: main.hl
exclude:
include:
parserOptions:
  showASTTree: stdout
  enableTracer: false
  disableTiming: true
  watchNode:
outDir: dist
targets:
  - vbs
